[logging]
level = "info"
directory = "./logs"

[finch]
# Product-specific config goes here.

[database]
# PostgreSQL connection URL. The environment variable DATABASE_URL takes precedence
# when using PostgresDataModule::from_env.
url = "postgresql://postgres:11akers32@192.168.88.10/finch"
